### ISSUE TITLE
Adjust instructions - Some users will be prompted to download .Net 

### ISSUE THREAD

**Issue by pmerriam** [SteveOhIo/unlockPdf#1]
Proposed new instructions inside angle brackets, below:

Simply extract this zip and run "unlockPdfInstaller.exe", choose a directory and hit install.
<If needed, the installer may also prompt you to download and install .Net from Microsoft.>
This package also comes bundled with an updates tool.

Right-click any pdf file or folder full of them and select to either lock or unlock, then enter the password and the program does it for you!

**Comment by SteveOhByte** [comment]
Added!
